ROOT_FOLDER :  "./"
DATASET_FOLDER : ""
VIT_FOLDER : ""
AUDIO_FOLDER: ""
AUDIO_FEATURE_EXTRACTOR: "MFCC"
VIDEO_FEATURE_EXTRACTOR: "VIT"
MODALILTIES: "VID+AUD"
AUD_HIDDEN_LAYERS: 1
VID_HIDDEN_LAYERS: 1
USE_SCHEDULER: 1
USE_XAVIER_INIT: 1
USE_RESIDUAL_BLOCKS: 1